In [1]:
import numpy as np
from tensorflow.keras.datasets import mnist
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1) Load MNIST
(X_tr_img, y_tr), (X_te_img, y_te) = mnist.load_data()

# 2) Flatten images: (28,28) -> (784,)
X_tr = X_tr_img.reshape(-1, 784).astype(np.float32)
X_te = X_te_img.reshape(-1, 784).astype(np.float32)

# 3) Scale pixels: 0-255 -> 0-1
X_tr = X_tr / 255.0
X_te = X_te / 255.0

print("Train:", X_tr.shape, "Test:", X_te.shape)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step
Train: (60000, 784) Test: (10000, 784)


In [2]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_tr, y_tr)

nb_pred = nb.predict(X_te)

print("=== Gaussian Naive Bayes (MNIST) ===")
print("Accuracy:", accuracy_score(y_te, nb_pred))
print("\nClassification Report:\n", classification_report(y_te, nb_pred))
print("Confusion Matrix:\n", confusion_matrix(y_te, nb_pred))


=== Gaussian Naive Bayes (MNIST) ===
Accuracy: 0.5558

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.89      0.84       980
           1       0.85      0.95      0.90      1135
           2       0.90      0.26      0.40      1032
           3       0.71      0.35      0.47      1010
           4       0.88      0.17      0.29       982
           5       0.55      0.05      0.09       892
           6       0.65      0.93      0.77       958
           7       0.88      0.27      0.42      1028
           8       0.28      0.67      0.40       974
           9       0.37      0.95      0.53      1009

    accuracy                           0.56     10000
   macro avg       0.69      0.55      0.51     10000
weighted avg       0.69      0.56      0.52     10000

Confusion Matrix:
 [[ 870    0    3    5    2    5   31    1   35   28]
 [   0 1079    2    1    0    0   10    0   38    5]
 [  79   25  266   91    5    2  269 

In [3]:
from sklearn.tree import DecisionTreeClassifier

# Use subset for speed
n_train = 20000
n_test  = 5000

dt = DecisionTreeClassifier(
    criterion="entropy",
    max_depth=25,          # prevents extreme overfitting
    min_samples_leaf=5,
    random_state=42
)

dt.fit(X_tr[:n_train], y_tr[:n_train])
dt_pred = dt.predict(X_te[:n_test])

print("=== Decision Tree (Entropy) — MNIST (Subset) ===")
print("Accuracy:", accuracy_score(y_te[:n_test], dt_pred))
print("\nClassification Report:\n", classification_report(y_te[:n_test], dt_pred))
print("Confusion Matrix:\n", confusion_matrix(y_te[:n_test], dt_pred))


=== Decision Tree (Entropy) — MNIST (Subset) ===
Accuracy: 0.8212

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.93      0.89       460
           1       0.93      0.95      0.94       571
           2       0.80      0.82      0.81       530
           3       0.77      0.81      0.79       500
           4       0.78      0.80      0.79       500
           5       0.80      0.76      0.78       456
           6       0.83      0.79      0.81       462
           7       0.88      0.86      0.87       512
           8       0.78      0.72      0.75       489
           9       0.79      0.76      0.77       520

    accuracy                           0.82      5000
   macro avg       0.82      0.82      0.82      5000
weighted avg       0.82      0.82      0.82      5000

Confusion Matrix:
 [[429   0   4   4   2   7   3   1   6   4]
 [  1 541   8   6   2   0   1   4   7   1]
 [ 12   8 437  11  15   4   8  18  14   3]
 [

In [4]:
from sklearn.neural_network import MLPClassifier

ann = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation="relu",
    max_iter=20,
    random_state=42
)

ann.fit(X_tr, y_tr)
ann_pred = ann.predict(X_te)

print("=== ANN (MLPClassifier) — MNIST ===")
print("Accuracy:", accuracy_score(y_te, ann_pred))
print("\nClassification Report:\n", classification_report(y_te, ann_pred))
print("Confusion Matrix:\n", confusion_matrix(y_te, ann_pred))


=== ANN (MLPClassifier) — MNIST ===
Accuracy: 0.9793

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.99      0.97      0.98      1032
           3       0.97      0.98      0.98      1010
           4       0.99      0.97      0.98       982
           5       0.99      0.98      0.98       892
           6       0.98      0.98      0.98       958
           7       0.98      0.97      0.98      1028
           8       0.97      0.97      0.97       974
           9       0.96      0.98      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

Confusion Matrix:
 [[ 969    1    0    0    1    0    3    1    3    2]
 [   0 1127    1    3    0    0    1    0    3    0]
 [   4    1 1006    4    2    0    2  

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
