In [1]:
import numpy as np

# ==== INPUT DATA ====
data = np.array([
    [0, 0, 1, 1],
    [1, 0, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 0, 1]
])

num_clusters = 2
learning_rate = 0.5
num_iterations = 100

# ==== GIVEN INITIAL WEIGHTS ====
weights = np.array([
    [0.2, 0.4, 0.6, 0.8],  # Cluster 1
    [0.9, 0.7, 0.5, 0.3]   # Cluster 2
]).T   # transpose to shape (4x2)

print("Initial Weights (Before Iteration):")
print(weights)

# ==== TRAINING LOOP ====
for it in range(num_iterations):
    for x in data:
        # Compute Euclidean distances (4D input vs 2 weight vectors)
        distances = np.linalg.norm(x - weights.T, axis=1)
        bmu_index = np.argmin(distances)

        # Update only the BMU weights
        weights[:, bmu_index] += learning_rate * (x - weights[:, bmu_index])

    if it == 0:
        print("\nWeights After First Iteration:")
        print(weights)

print("\nFinal Weights (After Last Iteration):")
print(weights)

# ==== CLUSTER ASSIGNMENT ====
print("\nCluster Assignments:")
for i, x in enumerate(data):
    distances = np.linalg.norm(x - weights.T, axis=1)
    cluster = np.argmin(distances)
    print(f"Input {i+1} {x} -> Cluster {cluster}")


Initial Weights (Before Iteration):
[[0.2 0.9]
 [0.4 0.7]
 [0.6 0.5]
 [0.8 0.3]]

Weights After First Iteration:
[[0.025 0.95 ]
 [0.3   0.35 ]
 [0.45  0.25 ]
 [0.725 0.15 ]]

Final Weights (After Last Iteration):
[[9.81818693e-92 1.00000000e+00]
 [2.85714286e-01 5.52202634e-31]
 [4.28571429e-01 3.94430453e-31]
 [7.14285714e-01 2.36658272e-31]]

Cluster Assignments:
Input 1 [0 0 1 1] -> Cluster 0
Input 2 [1 0 0 0] -> Cluster 1
Input 3 [0 1 1 0] -> Cluster 0
Input 4 [0 0 0 1] -> Cluster 0


In [3]:
!pip install minisom
from minisom import MiniSom
import numpy as np

# ==== INPUT DATA ====
data = np.array([
    [0, 0, 1, 1],
    [1, 0, 0, 0],
    [0, 1, 1, 0],
    [0, 0, 0, 1]
])

# ==== INITIALIZE SOM ====
som = MiniSom(x=1, y=2, input_len=4, sigma=0.5, learning_rate=0.5, random_seed=42)

# Manually set weights to your given values
custom_weights = np.array([
    [[0.2, 0.4, 0.6, 0.8]],
    [[0.9, 0.7, 0.5, 0.3]]
])
som._weights = np.transpose(custom_weights, (1, 0, 2))  # shape (1,2,4)

print("Initial Weights (Before Iteration):")
print(som.get_weights())

# ==== TRAIN 1 ITERATION ====
som.train_random(data, 1)
print("\nWeights After First Iteration:")
print(som.get_weights())

# ==== TRAIN FULL ====
som.train_random(data, 10)
print("\nFinal Weights (After Last Iteration):")
print(som.get_weights())

# ==== CLUSTER ASSIGNMENT ====
print("\nCluster Assignments:")
for i, x in enumerate(data):
    winner = som.winner(x)
    print(f"Input {i+1} {x} -> Cluster {winner}")


  Preparing metadata (setup.py) ... done
  Created wheel for minisom: filename=MiniSom-2.3.5-py3-none-any.whl size=12031 sha256=4d97159d770e3d698a3d9c1006a64525deb7797ae81b310f79204bde4c12b490
  Stored in directory: /root/.cache/pip/wheels/0f/8c/a4/5b7aa56fa6ef11d536d45da775bcc5a2a1c163ff0f8f11990b
Successfully built minisom
Initial Weights (Before Iteration):
[[[0.2 0.4 0.6 0.8]
  [0.9 0.7 0.5 0.3]]]

Weights After First Iteration:
[[[0.1        0.2        0.8        0.9       ]
  [0.83909912 0.65263265 0.53383382 0.34736735]]]

Final Weights (After Last Iteration):
[[[0.01683885 0.15453576 0.63243832 0.85699412]
  [0.81953921 0.25566833 0.24766131 0.07599428]]]

Cluster Assignments:
Input 1 [0 0 1 1] -> Cluster (np.int64(0), np.int64(0))
Input 2 [1 0 0 0] -> Cluster (np.int64(0), np.int64(1))
Input 3 [0 1 1 0] -> Cluster (np.int64(0), np.int64(0))
Input 4 [0 0 0 1] -> Cluster (np.int64(0), np.int64(0))
